[project]
name = "betting-ai"
version = "0.1.0"
description = ""
authors = [
    {name = "ferra12",email = "ferrazzo.edoardo@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic (>=2.11.9,<3.0.0)",
    "pydantic-settings (>=2.11.0,<3.0.0)",
    "pymongo (>=4.15.1,<5.0.0)",
    "pytest (>=8.4.2,<9.0.0)"
]

[tool.poetry]
packages = [{include = "betting_ai", from = "src"}]

[tool.black]
line-length = 88

[tool.flake8]
max-line-length = 88

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.3.0"

[tool.mypy]
explicit_package_bases = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
